add plugins to hyprexpo

diff --git a/dot_local/bin/executable_update b/dot_local/bin/executable_update
--- a/dot_local/bin/executable_update
+++ b/dot_local/bin/executable_update
@@ -46,7 +46,10 @@ elif command -v pacman &>/dev/null; then
 fi
 
 /usr/bin/hyprpm update
-
+if ! /usr/bin/hyprpm list | grep -q hyprexpo; then
+    echo "hyprexpo not found, adding it..."
+    /usr/bin/hyprpm add https://github.com/sandwichfarm/hyprexpo
+fi
 
 if [ -d $HOME/.config/burp/loader ]; then
     update-burp
