Fixes after a test install

diff --git a/dot_local/bin/executable_chezmoi-helpers-dconf b/dot_local/bin/executable_chezmoi-helpers-dconf
--- a/dot_local/bin/executable_chezmoi-helpers-dconf
+++ b/dot_local/bin/executable_chezmoi-helpers-dconf
@@ -3,33 +3,20 @@
 set -euo pipefail
 
 BASENAME=$(basename "$0")
-KEYFILE_TEMPLATE=$(chezmoi source-path)/dconf_overrides.keyfile.tmpl
 DCONF_PROFILE_DIR=$(systemd-path user-configuration)/dconf
 
 if [ $# -lt 1 ]; then
 	echo "usage: $BASENAME <command> [<args>]"
 	echo
 	echo "command must be one of"
-	echo "  dump    Dumps dconf keyfile with all custom overrides"
 	echo "  diff    Shows the changes that would occur if keyfile is applied"
 	echo "  apply   Applies keyfile to the default dconf user db"
 	echo
 	echo "SYNOPSIS"
-	echo "  $BASENAME dump"
 	echo "  $BASENAME diff [keyfile]"
 	echo "  $BASENAME apply [keyfile]"
-	echo
-	echo "DESCRIPTION"
-	echo "  The diff and apply commands accept an optional keyfile argument. When omitted,"
-	echo "  the operations implicitly assume a keyfile whose content is equivalent to the"
-	echo "  output of the dump command."
-
 	exit 0
 fi
-
-dump() {
-	chezmoi execute-template < "$KEYFILE_TEMPLATE"
-}
 
 diff() {
 	local keyfile="${1:-}"
@@ -41,16 +28,6 @@ diff() {
 	# Mirror user database to a temporary database
 	env DCONF_PROFILE="$tmp_profile" dconf load / < <(dconf dump /)
 
-	# Apply keyfile to temporary database
-	if [ -z "$keyfile" ]; then
-		env DCONF_PROFILE="$tmp_profile" dconf load / < <(dump)
-	elif [ -f "$keyfile" ]; then
-		env DCONF_PROFILE="$tmp_profile" dconf load / < "$keyfile"
-	else
-		echo "Keyfile not found: $keyfile"
-		exit 1
-	fi
-
 	git diff --no-index <(dconf dump /) <(env DCONF_PROFILE="$tmp_profile" dconf dump /)
 }
 
@@ -58,21 +35,15 @@ apply() {
 	local keyfile="${1:-}"
 
 	if [ -z "$keyfile" ]; then
-		dconf load / < <(dump)
-        echo "Keyfile applied"
+        echo "Keyfile not found: $keyfile"
+		exit 1
 	elif [ -f "$keyfile" ]; then
 		dconf load / < "$keyfile"
         echo "Keyfile $keyfile applied"
-	else
-		echo "Keyfile not found: $keyfile"
-		exit 1
-	fi
+    fi
 }
 
 case "$1" in
-	dump)
-		dump
-		;;
 	diff)
 		diff "${2:-}"
 		;;
